version: "3"
services:
    ganache:
        build: ./ganache
        ports:
            - "8545:8545"
            
    # dapp:
    #     build: ./dapp
    #     ports: 
    #         - "4000:4000"
    #     depends_on:
    #         - ganache
    
    dapp-front:
        build: ./client
        ports:
            - "8501:8501"
        networks:
            - ethflow_blockchain
        image: ethflow-front:latest
        container_name: ethflow_front
    #     depends_on:
    #         - dapp

networks:
    ethflow_blockchain:
        driver: bridge