version: "3"
services:
    ganache:
        container_name: ganache_ethstack
        build: ./ganache
        ports:
            - "8545:8545"
        networks:
            - ethflow
    
    dapp-back:
        container_name: dapp-back_ethstack
        build: ./API
        
        command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 5005
        
        ports: 
            - 5005:5005
        networks:
            - ethflow
        image: ethflow-back:latest
        container_name: ethflow_back
        depends_on:
            - ganache
    
    dapp-front:
        container_name: dappfront_ethstack
        build: ./client
        ports:
            - "8501:8501"
        networks:
            - ethflow
        image: ethflow-front:latest
        container_name: ethflow_front
        depends_on:
            - dapp-back

    geth-service:
        container_name: geth_ethstack
        build:
            context: ./ethereum
            dockerfile: dockerfile
        ports: 
            - "30303:30303"
        networks: 
            - ethflow
        image: ethflow-ethereum
        container_name: ethflow_ethereum

    db_users:
        container_name: postgres_ethflow
        build:
            context: ./postgres
            dockerfile: Dockerfile
        image: ethflow-postgresql  
        ports: 
            - "5432:5432" 
        restart: always
        volumes:
        - ./postgres/db_data:/var/lib/postgresql/data
        env_file: 
            - ./postgres/.env

    db_dashboard:
        container_name: pgadmin4_ethflow
        build:
            context: ./pgadmin
            dockerfile: Dockerfile
        image: ethflow-pgadmin4
        restart: always
        volumes:  
        - ./pgadmin/pgadmin_data:/var/lib/pgadmin
        env_file:
          - ./pgadmin/.env
        ports:
          - "5050:80"    
    
    hasura:
        image: hasura/graphql-engine:latest.cli-migrations-v2
        volumes:
            - ./hasura/migrations:/hasura-migrations
            - ./hasura/metadata:/hasura-metadata
        container_name: blog-hasura
        restart: always
        depends_on:
            - 'postgres'
            - 'django'
        environment:
            HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
            HASURA_GRAPHQL_DEV_MODE: 'true'
            HASURA_GRAPHQL_UNAUTHORIZED_ROLE: 'public'
            HASURA_GRAPHQL_DATABASE_URL: 'postgres://postgres:password@postgres:5432/postgres'
            HASURA_GRAPHQL_ADMIN_SECRET: 'password'
            HASURA_GRAPHQL_JWT_SECRET: '{ "type": "HS256", "key": "Q3d5ymmEjNBw37XQdL4xeRVvDCxgvqFrisALR4bng-0" }' # *** CHANGE THIS ***
        ports:
            - "8080:8080"

networks:
    ethflow:
        driver: bridge