version: "3"
services:
    ganache:
        build: ./ganache
        ports:
            - "8545:8545"
        networks:
            - ethflow
    
    dapp-back:
        build: ./API
        
        command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 5005
        
        ports: 
            - 5005:5005
        networks:
            - ethflow
        image: ethflow-back:latest
        container_name: ethflow_back
        depends_on:
            - ganache
    
    dapp-front:
        build: ./client
        ports:
            - "8501:8501"
        networks:
            - ethflow
        image: ethflow-front:latest
        container_name: ethflow_front
        depends_on:
            - dapp-back

    geth-service:
        build:
            context: ./ethereum
            dockerfile: dockerfile
        ports: 
            - "30303:30303"
        networks: 
            - ethflow
        image: ethflow-ethereum
        container_name: ethflow_ethereum

networks:
    ethflow:
        driver: bridge